package in.partake.service;

import in.partake.model.dto.UserTwitterLink;
import in.partake.session.TwitterLoginInformation;
import twitter4j.TwitterException;

public interface ITwitterService {
    public TwitterLoginInformation createLoginInformation(String redirectURL) throws TwitterException;
    public UserTwitterLink createTwitterLinkageFromLoginInformation(TwitterLoginInformation information, String verifier) throws TwitterException;

    public void updateStatus(String token, String tokenSecret, String message) throws TwitterException;
    /** Sends a direct message from the user generated by accessToken to the user whose twitterId is <code>twitter</code> */
    public void sendDirectMesage(String token, String tokenSecret, long twitterId, String message) throws TwitterException;
}
